### ISSUE TITLE
Edit lookup fails - internal server error

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-content-proxy#279]
For valid page: https://blog.adobe.com/en/2020/12/01/what-does-the-cmo50-tell-us-about-modern-marketing.html#gs.re0ega

Edit URL: https://adobeioruntime.net/api/v1/web/helix/helix-services/content-proxy@v2?owner=adobe&repo=theblog&ref=master&path=%2F&edit=https%3A%2F%2Fblog.adobe.com%2Fen%2F2020%2F12%2F01%2Fwhat-does-the-cmo50-tell-us-about-modern-marketing.html%23gs.re0ega

returns `Internal Server Error`.

Activation logs:

```bash
wsk activation logs fc8055048cc24fc38055048cc22fc32c
2021-01-28T10:17:37.385Z       stdout: instrumenting epsagon.
2021-01-28T10:17:37.386Z       stdout: action-status-begin {"container":{"uuid":"1329520efe5a0d3b619c117839e97724","numInvocations":6,"begin":{"mem":174407680,"age":174227,"concurrency":1}}}
2021-01-28T10:17:37.956Z       stderr: [WARN] StatusCodeError
    at Function.fromError (/nodejsAction/VNX8IJnR/index.js:5135:17)
    at OneDrive.listChildren (/nodejsAction/VNX8IJnR/index.js:4387:37)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  statusCode: 404,
  details: { code: 'itemNotFound', message: 'The resource could not be found.', innerError: { date: '2021-01-28T10:17:37', 'request-id': 'd697e254-021b-480f-9da2-230f67002e79', 'client-request-id': 'd697e254-021b-480f-9da2-230f67002e79' } }
}
2021-01-28T10:17:37.958Z       stderr: [ERROR] error {
  params: {},
  error: StatusCodeError
      at Function.fromError (/nodejsAction/VNX8IJnR/index.js:5135:17)
      at OneDrive.listChildren (/nodejsAction/VNX8IJnR/index.js:4387:37)
      at processTicksAndRejections (internal/process/task_queues.js:97:5) {
    statusCode: 404,
    details: { code: 'itemNotFound', message: 'The resource could not be found.', innerError: { date: '2021-01-28T10:17:37', 'request-id': 'd697e254-021b-480f-9da2-230f67002e79', 'client-request-id': 'd697e254-021b-480f-9da2-230f67002e79' } }
  }
}
2021-01-28T10:17:37.959Z       stderr: error while invoking function TypeError: Cannot read property 'get' of undefined
    at ensureUTF8Charset (/nodejsAction/VNX8IJnR/index.js:579:29)
    at openwhisk (/nodejsAction/VNX8IJnR/index.js:231:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /nodejsAction/VNX8IJnR/index.js:716:14
    at async NodeActionRunner.userScriptMain (/nodejsAction/VNX8IJnR/index.js:853:15)
2021-01-28T10:17:37.959Z       stdout: action-status-end {"container":{"uuid":"1329520efe5a0d3b619c117839e97724","numInvocations":6,"begin":{"mem":174407680,"age":174227,"concurrency":1},"end":{"mem":175591424,"age":174800,"concurrency":1},"delta":{"mem":1183744,"age":573}}}
```

**Comment by kptdobe** [comment]
Ok, the resource does not exist (missing `/publish` in the path) but I think the response could be nicer than "Internal Server Error".
