### ISSUE TITLE
invalid sharelink gives 500

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-content-proxy#318]
**Description**
an illegal sharelink returns a 500 with our nice broken 500 page:

```
StatusCodeError at Function.fromError (/nodejsAction/tsfszb1w/index.js:8779:17) at OneDrive.resolveShareLink (/nodejsAction/tsfszb1w/index.js:7983:37) at processTicksAndRejections (internal/process/task_queues.js:97:5) { statusCode: 400, details: { code: 'invalidRequest', message: 'The sharing token is invalid.', innerError: { date: '2021-03-10T12:39:23', 'request-id': 'd6ca86c4-26d0-4676-b128-913bd085647b', 'client-request-id': 'd6ca86c4-26d0-4676-b128-913bd085647b' } } 
```

which is a bit hard to understand by a new user. maybe return a text:

```
500 Internal Server Error

Invalid fstab
```

**Comment by tripodsan** [comment]
can't reproduce anymore
