### ISSUE TITLE
timeout leads to error logged in epsagon

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-content-proxy#59]
**Description**
A timeout error throws an exception which is not caught inside the main function and leads to an error reported in epsagon. so far, all other actions handle their exceptions internally.

```
2020-06-14T07:33:01.787Z       stderr: [ERROR] error { params: { path: '/en/drafts/migrated/2013/07/30/7-main-benefits-closedloop-marketing.md', __ow_method: 'get', ref: 'd43fd8683f7fd8fcf04755ae3cf23f46cc02c509', __ow_headers: { accept: 'application/json, text/*;q=0.9, */*;q=0.8', 'accept-encoding': 'br, gzip;q=0.8, deflate;q=0.5', connection: 'close', 'epsagon-trace-id': '8cb3499e26574249b0b5851c81e1fee7:be3b5057894b6d00:8a248b4a1c372e3f:1', host: 'controller-a', 'perf-br-req-in': '1592119960.014', 'user-agent': 'helix-fetch', 'x-cdn-request-id': '70bf3936-2ac7-57f9-ab20-d80672b19b41', 'x-cdn-url': 'https://theblog-adobe.project-helix.page/en/drafts/migrated/2013/07/30/7-main-benefits-closedloop-marketing.html', 'x-forwarded-for': '52.30.165.11, 10.250.206.51', 'x-forwarded-host': 'adobeioruntime.net', 'x-forwarded-port': '443', 'x-forwarded-proto': 'https', 'x-real-ip': '10.250.206.51', 'x-request-id': '70bf3936-2ac7-57f9-ab20-d80672b19b41' }, __ow_path: '', owner: 'adobe', repo: 'theblog' }, error: Error: GET https://adobeioruntime.net/api/v1/web/helix/helix-services/word2md@v1?path=%2Fen%2Fdrafts%2Fmigrated%2F2013%2F07%2F30%2F7-main-benefits-closedloop-marketing.docx&shareLink=https%3A%2F%2Fadobe.sharepoint.com%2Fsites%2FTheBlog%2FShared%2520Documents%2Ftheblog&rid=70bf3936-2ac7-57f9-ab20-d80672b19b41&src=adobe%2Ftheblog%2Fd43fd8683f7fd8fcf04755ae3cf23f46cc02c509 timed out after 20000 ms
       at timeoutError (/nodejsAction/HmeHxYJZ/main.js:58212:16)
       at Timeout.setTimeout [as _onTimeout] (/nodejsAction/HmeHxYJZ/main.js:58235:28)
       at ontimeout (timers.js:436:11)
       at tryOnTimeout (timers.js:300:5)
       at listOnTimeout (timers.js:263:5)
       at Timer.processTimers (timers.js:223:10) }
```

The timeout error is thrown from within helix-fetch.

**Comment by trieloff** [comment]
@stefan-guggisberg any recommendations how to catch that one?

**Comment by stefan-guggisberg** [comment]
> any recommendations how to catch that one?

@trieloff wrap `fetch` call in `try/catch` block: https://github.com/adobe/helix-fetch/blob/master/test/index.test.js#L414-L420
